---
- name: Create Directory structure
  command: mkdir -p /home/user/tmp

- name: Copy required packages
  copy:
    src: /home/user/task03/ansible/files/
    dest: /home/user/tmp
    force: no
#    directory_mode: yes
#    remote_src: yes
