---
- hosts: node04
#  vars_files:
#    - group_vars/vars.yml
  remote_user: root
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Create folder for scripts
      file:
        path: /opt/scripts
        state: directory
    - name: Transfer the script
      copy:
        src: "{{ playbook_dir }}/files/check.sh.j2"
        dest: /opt/scripts/check.sh
        mode: 0777
    - name: Check status of ELK and Nginx
      command: sh /opt/scripts/check.sh -v
#      register: elk
#    - debug: var=elk.stdout_lines
