---
- hosts: "{{ elk_name }}"
  vars_files:
    - group_vars/deploy.yml
  remote_user: root
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Define action variable
      set_fact:
        action_name: ""
      when: action is undefined

    - name: Define pattern variable
      set_fact:
        pattern: ""
      when: pattern is undefined

    - name: Transfer the script (index_management)
      template:
        src=index_management.sh.j2
        dest=/opt/scripts/index_management.sh
        owner=root
        group=root
        mode=0777

    - name: Manage ELK indices
      shell: /opt/scripts/index_management.sh "{{ action_name }}" "{{ pattern }}"
      register: manage_indices
    - debug: var=manage_indices.stdout_lines

    #  sh /opt/scripts/index_management.sh
    # {{ action_name }} {{ pattern_name }}
