---
#
# Installing logstash
#
# Install Nginx
- name: Install Logstash rpm from a local file
  yum:
    name: "{{ remote_repo_path }}/{{ logstash_package }}"
# Creating certs directories for SSL
- name: Creates SSL directories
  file:
    path: /etc/pki/tls/certs
    state: directory
# Creating private directories for SSL
- name: Creates SSL directories
  file:
    path: /etc/pki/tls/private
    state: directory
# Check OpenSSL SANs (SubjectAltName) entry for CA
- name: Check OpenSSL SANs (SubjectAltName) entry for CA
  shell: grep "{{ elk_ip }}" /etc/pki/tls/openssl.cnf | wc -l
  ignore_errors: true
  register: subjectAltName_exists
#Add OpenSSL SANs (SubjectAltName) entry for CA
- name: Add OpenSSL SANs (SubjectAltName) entry for CA
  lineinfile:
    dest: /etc/pki/tls/openssl.cnf
    line: 'subjectAltName = "IP:{{ elk_ip }}"'
    regexp: '^ Extensions for a typical CA'
    insertbefore: '# Extensions for a typical CA'
    backup: yes
  when: subjectAltName_exists.stdout|int == 0
# Update SSL to allow outside access
#- name: Updating the config file to restrict outside access
#  lineinfile:
#    destfile: /etc/ssl/openssl.cnf
#    regexp: 'subjectAltName ='
#    line: 'subjectAltName = IP: {{ elk_ip }}'
#    create: yes
# Generate SSL certificates for Logstash
- name: Generate SSL certificates
  shell: "[ -f /etc/pki/tls/certs/logstash-forwarder.crt ] || openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt"
# Configure Beats input configuration 02-beats-input.conf
- name: Configure Beats configuration file
  template:
    src=beats-input.conf.j2
    dest=/etc/logstash/conf.d/02-beats-input.conf
    owner=root
    group=root
    mode=0644
# Configure Logstash 10-syslog-filter.conf config file
- name: Configure Syslog Filter
  template:
    src=syslog-filter.conf.j2
    dest=/etc/logstash/conf.d/10-syslog-filter.conf
    owner=root
    group=root
    mode=0644
# Configure Elasticsearch output file 30-elasticsearch-output.conf
- name: Configure Elasticsearch output file
  template:
    src=elasticsearch-output.conf.j2
    dest=/etc/logstash/conf.d/30-elasticsearch-output.conf
    owner=root
    group=root
    mode=0644
# Update kibana config file to allow outside access
- name: Updating the config file to allow outside access
  lineinfile:
    destfile: /etc/logstash/logstash.yml
    regexp: 'http.host:'
    line: "http.host: \"{{ elk_ip }}\""
 # Enable Logstash service
- name: Enable Logstash service
  systemd:
    name: logstash
    enabled: yes
    daemon_reload: yes
# Start Logstash service
- name: Start Logstash service
  systemd:
    name: logstash
    state: started
